config/routes.rb
Rails.application.routes.draw do
  
  resources :roster_lists
  namespace :admin do
   #resources :users
    #resources :posts
   # resources :admin_users
    #resources :contacts
    resources :employees
    resources :employee_notes
    resources :expense_codes
    resources :perdiems
   # resources :projects
    resources :project_types
   # resources :rosters
   # resources :schedules
    #resources :shifts
    resources :travel_infos
    resources :clients
    resources :gc_contacts
    resources :project_managers
    resources :shift_managers
    resources :site_managers

    root to: "clients#index"  
  end

  resources :travel_infos
  resources :shifts
  resources :schedules
  
  
  
  

  resources :employee_lists
  

  resources :project_types
  resources :perdiems
  resources :expense_codes
  resources :projects 
    resources :rosters do
    resources :roster_lists 
   end

  
   
  resources :contacts
  resources :posts
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: 'projects#index'

  get 'new_store', :to => 'projects#new_store'
  get 'els', :to => 'projects#els'
  get 'fet', :to => 'projects#fet'

  get 'per_diem_info', :to => 'roster_lists#per_diem_info'

  get 'project_shifts', :to => 'projects#project_shifts'


  resources  'copy_roster_list', :to => 'rosters#copy_roster_list'
 

end

app/models/admin_user.rb
class AdminUser < User 
end

app/models/client.rb
class Client < Contact
	has_many :projects
end

app/models/contact.rb
class Contact < ApplicationRecord
end

app/models/employee.rb
class Employee < ApplicationRecord

has_many :perdiems
has_many :expense_codes
has_many :roster_lists


 def full_name
  	last_name.upcase + ", " + first_name.upcase
  end

end

app/models/employee_list.rb
class EmployeeList < ApplicationRecord
  belongs_to :roster
  has_many :expense_codes
  has_many :per_diems
  has_many :employees
end

app/models/expense_code.rb
class ExpenseCode < ApplicationRecord
  belongs_to :employee_list
end

app/models/gc_contact.rb
class GcContact < Contact 
end

app/models/perdiem.rb
class Perdiem < ApplicationRecord
  belongs_to :employee_list
end

app/models/post.rb
class Post < ActiveRecord::Base
	belongs_to :user , optional: true
	validates_presence_of :date, :rationale
end

app/models/project.rb
class Project < ApplicationRecord

	has_one :project_types
	has_many :rosters, inverse_of: :project
	has_many :travel_infos
	has_many :schedules
	has_many :states
	

	# class to combine columns to create project name
	def project_name
		company + project_type.to_s + client + store_num
	end


	def self.search(term)
	  if term
	    where('project_type LIKE ? OR client LIKE ?', "%#{term}%", "%#{term}%" )
	    
	  else
	    all
	  end
	end

end

app/models/project_type.rb
class ProjectType < ApplicationRecord

end

app/models/roster.rb
class Roster < ApplicationRecord
  belongs_to :project 
  has_many :roster_lists, :dependent => :destroy
  has_many :shift_infos
accepts_nested_attributes_for :roster_lists ,
							   allow_destroy: true,
							   reject_if: proc {|att| att['employee_id'].blank?}


def self.search(term)

	  if term
	    where("week = ?", "%#{term}%")
	      	    
	  else
	    all
	  end
	end

							  
end

app/models/roster_list.rb
class RosterList < ApplicationRecord
  belongs_to :roster, optional: true
  belongs_to :employee


def self.search(term)

	  if term
	    where("week = ?", "%#{term}%")
	      	    
	  else
	    all
	  end
	end



end

app/models/schedule.rb
class Schedule < ApplicationRecord
  belongs_to :project
  has_many :shifts
end

app/models/shift.rb
class Shift < ApplicationRecord
  belongs_to :schedule
  has_many :employees
end

app/models/shift_info.rb
class ShiftInfo < ApplicationRecord
  belongs_to :roster
end

app/models/site_manager.rb
class SiteManager < Contact
end

app/models/state.rb
class State < ApplicationRecord
  has_many :project
end

app/models/travel_info.rb
class TravelInfo < ApplicationRecord
  belongs_to :project
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :posts
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates_presence_of :first_name, :last_name

  def full_name
  	last_name.upcase + "," + first_name.upcase
  end
end

app/controllers/rosters_controller.rb
class RostersController < ApplicationController
	before_action :set_rosters, only: [:show, :edit, :update,
	 :destroy, :search, :copy_roster_list]
	 
def index
#@rosters = Roster.search(params[:term])
@rosters = Roster.all
#@rosters = @rosters.joins(:roster_lists).order(:shift_id)

end



def new
	 #  @project = Project.find(params[:project_id])

	    @roster = Roster.new
	   
	    3.times do 
	    	@roster.roster_lists.build
	    end
	 #  respond_to do |format|
   
      #  format.html 
       # format.json# { render :json => @roster_list }
   #  
    
   # end
  end
	


 def create
 	@roster = Roster.new(roster_params)
 	if @roster.save
			redirect_to @roster, notice: 'Your new roster was created successfully'
		else
			render :new
		end
	end

def edit
	@test = params
 # @project = Project.find(params[:id])
	end

def show
end


def copy_roster_list

	# @check_for_nil = @roster.roster_lists.all.inspect  
	# @next_roster_id  = @roster.roster_lists.first.roster_id + 1 
	# @roster_lists = RosterList.where(:roster_id => @next_roster_id) 
    @roster.roster_lists.each do |roster_list| 
       roster_list.roster_id = roster_list.roster_id + 1         
         @roster_list = RosterList.create(roster_list.attributes.except("id"))
  		end
  # 		if @roster_list.save
			redirect_to root_path , notice: 'Your new roster was created successfully'
	#	else
	#		
	#	end
end  

def update
	      
    respond_to do |format|
      if @roster.update(roster_params)
        format.html { redirect_to project_path(@roster.project_id), notice: 'Roster was successfully updated.' }
        format.json { render :show, status: :ok, location: @roster}
      else
        format.html { render :edit }
        format.json { render json: @roster.errors, status: :unprocessable_entity }
      end
    end
  end



def destroy

end

private

def set_rosters
#s@project = Project.find(params[:id])
@roster = Roster.find(params[:id])


end


def roster_params
	params.require(:roster).permit(:project_id, :week , :term, 
		roster_lists_attributes: [:id, :employee_id, :perdiem, :copy_roster_list, :expense_code, :shift_id, :destroy, :search ])
end

def roster_list_params
      params.require(:roster_list).permit(:roster_id, :employee_id, :perdiem, :expense_code, :shift_id, :destroy)
    end


end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/rosters_helper.rb
module RostersHelper
end

app/views/rosters/_form.html.erb
<%= simple_form_for @roster do |f| %>
 <div class "form-inputs">
<p > <%= @roster.project.project_name  %>   </p>
 
   </div>

    <table class = "table table-striped table-hover" >
      <thead>
        <tr>
          <th> </th>
          <th>Name </th>
          <th>Per Diem </th>
          <th>Expense Code </th>
          <th> Shift </th>
        </tr>
      </thead>

      <tbody class = "employees">
           <%= f.fields_for :roster_lists do |builder| %>
           <%= render 'roster_list_fields', f: builder %>
        <% end %>
</tbody>
</table>

<div class = "form-action">
    <%= f.submit "Submit" %>
    <%= link_to_add_association 'Add Employee', f, :roster_lists, class: 'btn btn-primary', data: {
      association_insertion_node: '.employees', association_insertion_method: :append  } %>
  </div>
<% end %>

app/views/rosters/_roster_list_fields.html.erb
<tr class = "nested-fields">
	<td> 
		<%= link_to_remove_association "Remove Employee", f , class: 'btn btn-primary btn-xs'  %>
	</td>
   		<td> <%= f.association :employee, label_method: :full_name , label: false%> </td>
   		<td> <%= f.input :perdiem , label: false%> </td>
   		<td> <%= f.input :expense_code, label: false %> </td>
        <td> <%= f.input :shift_id , label: false , input_html:{min: '1', step: 'any'}%> </td>
   	</tr>

app/views/rosters/copy_roster_list.html.erb
Roster info

<%  @check_for_nil = @roster.roster_lists.all.inspect  %>

<% @next_roster_id  = @roster.roster_lists.first.roster_id + 1 %>

<% @roster_lists = RosterList.where(:roster_id => @next_roster_id) %>

# <%  if @roster_lists.exists?  %>

    <p>  List needs to be updated <p>

 

     <% @roster.roster_lists.each do |roster_list| %>

        <% roster_list.roster_id = roster_list.roster_id + 1 %> 

        <%= roster_list.inspect %>


        <% end %>  


 






    
 <% else %> 

 	<p> list needs to be created  </p>



  
     <% @roster.roster_lists.each do |roster_list| %>

        <% roster_list.roster_id = roster_list.roster_id + 1 %> 

        <%= roster_list.inspect %>


        <% end %>  




 	<% end %> 




 

app/views/rosters/edit.html.erb
<div class = "panel panel-primary">


<div class="panel-heading">
 Add & Edit Roster --->  Week of: <%= @roster.week.strftime('%m/%d/%Y') %> 
  </div>



	<div class="panel-body">
	<%= render 'form', roster: @roster %>
	<br>
 <%= link_to 'Back',  project_path(@roster.project_id)%>
	
	</div> 
</div

app/views/rosters/index.html.erb
<div class="jumbotron">

<h2>Rosters %>  </h2>

<%= form_tag(rosters_path , method: :get) do %>
  <%= date_field_tag :term, params[:term] %>
  <%= submit_tag 'Search', name: nil %>
<% end %>

<table class="table table-striped table-hover">
	<thead>
		<tr>
			<th> 	Project ID	</th>
			<th>	Project Name</th>
			<th>    Week      </th>
			<th>    Roster ID </th>
			<th>             </th>
		</tr>
	</thead>
	<tbody>
		  <% @rosters.each do |roster| %>
		  <tr>
		  	 <td> <%= roster.project_id %> </td>	
		  <td> <%= roster.project.project_name %> </td>	
        <td><%= roster.week%></td>
         
        <td><%= roster.id %></td>
        
             <td><%= link_to "<i class='glyphicon glyphicon-plus'> </i>".html_safe, 
             roster_path(roster) %></td>
    </tr>


    <% end %> 

	</tbody>
</table>

app/views/rosters/new.html.erb
<div class = "jumbotron">

<h3> Add Roster </h3>

<br>
<br>

<%= render 'form' %>

</div>

app/views/rosters/show.html.erb
<div class = "panel panel-primary form-panel project">


<div class="panel-heading"> <%= @roster.project.project_name  %> </div>

 <%= @roster.project.num_of_shifts.times do ||%>

<table class = "table table-striped table-hover">
  <thead>
    <tr>
      
      <th>Employee</th>
      <th>Phone</th>
      <th> Per Diem </th>
      <th> Expense Code </th>
      <th> Shift </th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>



<% for list in @roster.roster_lists.order(:shift_id)%>




  <div class="panel-body">

<tr>
<td> <%= list.employee.full_name %> </td>
<td> <%= list.employee.phone %> </td>
<td> <%= list.perdiem%> </td>
<td> <%= list.expense_code %> </td>
<td> <%= list.shift_id %> </td>
</tr>
<% end %>


 </tbody>
</table>
<%= end %> 
<td><%= link_to 'Add Employee',    new_roster_roster_list_path(@roster) %></td>

<td><%= link_to 'Back to Project',    project_path(@roster.project) %></td>

				      
         </div>
</div>
</div>




         