config/routes.rb
Rails.application.routes.draw do
  
  resources :roster_lists
  namespace :admin do
   #resources :users
    #resources :posts
   # resources :admin_users
    #resources :contacts
    resources :employees
    resources :employee_notes
    resources :expense_codes
    resources :perdiems
   # resources :projects
    resources :project_types
   # resources :rosters
   # resources :schedules
    #resources :shifts
    resources :travel_infos
    resources :clients
    resources :gc_contacts
    resources :project_managers
    resources :shift_managers
    resources :site_managers

    root to: "clients#index"  
  end

  resources :travel_infos
  resources :shifts
  resources :schedules
  
  
  
  

  resources :employee_lists
  

  resources :project_types
  resources :perdiems
  resources :expense_codes
  resources :projects 
    resources :rosters do
    resources :roster_lists 
   end

  
   
  resources :contacts
  resources :posts
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: 'projects#index'

  get 'new_store', :to => 'projects#new_store'
  get 'els', :to => 'projects#els'
  get 'fet', :to => 'projects#fet'

  get 'per_diem_info', :to => 'roster_lists#per_diem_info'

  get 'project_shifts', :to => 'projects#project_shifts'


  resources  'copy_roster_list', :to => 'rosters#copy_roster_list'
 

end

app/models/admin_user.rb
class AdminUser < User 
end

app/models/client.rb
class Client < Contact
	has_many :projects
end

app/models/contact.rb
class Contact < ApplicationRecord
end

app/models/employee.rb
class Employee < ApplicationRecord

has_many :perdiems
has_many :expense_codes
has_many :roster_lists


 def full_name
  	last_name.upcase + ", " + first_name.upcase
  end

end

app/models/expense_code.rb
class ExpenseCode < ApplicationRecord
  belongs_to :employee_list
end

app/models/gc_contact.rb
class GcContact < Contact 
end

app/models/perdiem.rb
class Perdiem < ApplicationRecord
  belongs_to :employee_list
end

app/models/post.rb
class Post < ActiveRecord::Base
	belongs_to :user , optional: true
	validates_presence_of :date, :rationale
end

app/models/project.rb
class Project < ApplicationRecord

	has_one :project_types
	has_many :rosters, inverse_of: :project
	has_many :travel_infos
	has_many :schedules
	has_many :states
	

	# class to combine columns to create project name
	def project_name
		company + project_type.to_s + client + store_num
	end


	def self.search(term)
	  if term
	    where('project_type LIKE ? OR client LIKE ?', "%#{term}%", "%#{term}%" )
	    
	  else
	    all
	  end
	end

end

app/models/project_type.rb
class ProjectType < ApplicationRecord

end

app/models/roster.rb
class Roster < ApplicationRecord
  belongs_to :project 
  has_many :roster_lists, :dependent => :destroy
  has_many :shift_infos
accepts_nested_attributes_for :roster_lists ,
							   allow_destroy: true,
							   reject_if: proc {|att| att['employee_id'].blank?}


def self.search(term)

	  if term
	    where("week = ?", "%#{term}%")
	      	    
	  else
	    all
	  end
	end

							  
end

app/models/roster_list.rb
class RosterList < ApplicationRecord
  belongs_to :roster, optional: true
  belongs_to :employee


def self.search(term)

	  if term
	    where("week = ?", "%#{term}%")
	      	    
	  else
	    all
	  end
	end



end

app/models/schedule.rb
class Schedule < ApplicationRecord
  belongs_to :project
  has_many :shifts
end

app/models/shift.rb
class Shift < ApplicationRecord
  belongs_to :schedule
  has_many :employees
end

app/models/shift_info.rb
class ShiftInfo < ApplicationRecord
  belongs_to :roster
end

app/models/site_manager.rb
class SiteManager < Contact
end

app/models/state.rb
class State < ApplicationRecord
  has_many :project
end

app/models/travel_info.rb
class TravelInfo < ApplicationRecord
  belongs_to :project
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :posts
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates_presence_of :first_name, :last_name

  def full_name
  	last_name.upcase + "," + first_name.upcase
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/admin/application.html.erb
<%#
# Application Layout

This view template is used as the layout
for every page that Administrate generates.

By default, it renders:
- Navigation
- Content for a search bar
  (if provided by a `content_for` block in a nested page)
- Flashes
- Links to stylesheets and JavaScripts
%>

<!DOCTYPE html>
<html lang="<%= I18n.locale %>">
<head>
  <meta charset="utf-8">
  <meta name="ROBOTS" content="NOODP">
  <meta name="viewport" content="initial-scale=1">
  <title>
    <%= content_for(:title) %> - <%= Rails.application.class.parent_name.titlecase %>
  </title>

  <%= render "stylesheet" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render "icons" %>

  <div class="app-container">
    <%= render "navigation" -%>

    <main class="main-content" role="main">
      <%= render "flashes" -%>
      <%= yield %>
    </main>
  </div>

  <%= render "javascript" %>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TabRetailNew</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

  	<div class="container">
		<div class="row">
			<div class="col-md-12">
				<%= render 'shared/nav' %>
			    <%= yield %>

			</div>
		</div>
	</div>

<%= js add_gritter(flash[:notice], title: "Tab Retail App Notification", sticky: false) %>
  </body>
</html>

app/views/shared/_nav.html.erb
<div class = 'logo'>
	<%= image_tag 'tab_logo_main.png' %> 
	
</div> 


<ul class="custom-nav nav nav-tabs">
	<li class="<%= active?(root_path) %>">
		<%= link_to "Home", root_path %>
	</li>

	<li class="<%= active?(new_project_path) %>">
		<%= link_to "Add Project", new_project_path %>
	</li>
	
<li class="dropdown">

		 <a href="#" data-toggle="dropdown" class="dropdown-toggle">Tab Retail<strong class="caret"></strong></a>
		<ul class="dropdown-menu">
			<li>
				<%= link_to "New Store", new_store_path %>
			</li>

			
			
			<li>
				<%= link_to "Remodel", "" %>
			</li>

			<li>
				<%= link_to "Resteel", "" %>
			</li>

			<li>
				<%= link_to "Special Project", "" %>
			</li>
<li>
				<%= link_to "Backroom SP", "" %>
			</li>

			<li>
				<%= link_to "ELS", els_path %>
			</li>

<li>
				<%= link_to "FET", fet_path %>
			</li>

			<li>
				<%= link_to "Bike Rack SP", "" %>
			</li>

			<li>
				<%= link_to "Tire Mezz", "" %>
			</li>
			
		</ul>
	</li>


<li class="dropdown">
		 <a href="#" data-toggle="dropdown" class="dropdown-toggle">Ridgeline<strong class="caret"></strong></a>
		<ul class="dropdown-menu">
			<li>
				<%= link_to "New Store", root_path %>
			</li>

			
			
			<li>
				<%= link_to "Remodel", "" %>
			</li>

			<li>
				<%= link_to "Resteel", "" %>
			</li>

			<li>
				<%= link_to "Special Project", "" %>
			</li>
<li>
				<%= link_to "Backroom SP", "" %>
			</li>

			<li>
				<%= link_to "ELS", "" %>
			</li>

<li>
				<%= link_to "FET", "" %>
			</li>

			<li>
				<%= link_to "Bike Rack SP", "" %>
			</li>

			<li>
				<%= link_to "Tire Mezz", "" %>
			</li>
			
		</ul>
	</li>

<li class="dropdown">
		 <a href="#" data-toggle="dropdown" class="dropdown-toggle">TRS<strong class="caret"></strong></a>
		<ul class="dropdown-menu">
			<li>
				<%= link_to "New Store", root_path %>
			</li>

			
			
			<li>
				<%= link_to "Remodel", "" %>
			</li>

			<li>
				<%= link_to "Resteel", "" %>
			</li>

			<li>
				<%= link_to "Special Project", "" %>
			</li>
<li>
				<%= link_to "Backroom SP", "" %>
			</li>

			<li>
				<%= link_to "ELS", "" %>
			</li>

<li>
				<%= link_to "FET", "" %>
			</li>

			<li>
				<%= link_to "Bike Rack SP", "" %>
			</li>

			<li>
				<%= link_to "Tire Mezz", "" %>
			</li>
			
		</ul>
	</li>

	<li class="dropdown">
		 <a href="#" data-toggle="dropdown" class="dropdown-toggle">StoreForce<strong class="caret"></strong></a>
		<ul class="dropdown-menu">
			<li>
				<%= link_to "New Store", root_path %>
			</li>

			
			
			<li>
				<%= link_to "Remodel", "" %>
			</li>

			<li>
				<%= link_to "Resteel", "" %>
			</li>

			<li>
				<%= link_to "Special Project", "" %>
			</li>
<li>
				<%= link_to "Backroom SP", "" %>
			</li>

			<li>
				<%= link_to "ELS", "" %>
			</li>

<li>
				<%= link_to "FET", "" %>
			</li>

			<li>
				<%= link_to "Bike Rack SP", "" %>
			</li>

			<li>
				<%= link_to "Tire Mezz", "" %>
			</li>
			
		</ul>
	</li>




	<li class="dropdown pull-right">
		 <a href="#" data-toggle="dropdown" class="dropdown-toggle">
		 <i class='glyphicon glyphicon-cog'> </i>	<strong class="caret"></strong></a>
		<ul class="dropdown-menu">
			<li>
				<%= link_to "Admin Dashboard", admin_root_path %>
			</li>

			
			<li class="divider">
			</li>
			<li>
				<%= link_to "Logout", destroy_user_session_path, method: :delete %>
			</li>
		</ul>
	</li>
</ul>