config/routes.rb
Rails.application.routes.draw do
  
  resources :roster_lists
  namespace :admin do
   #resources :users
    #resources :posts
   # resources :admin_users
    #resources :contacts
    resources :employees
    resources :employee_notes
    resources :expense_codes
    resources :perdiems
   # resources :projects
    resources :project_types
   # resources :rosters
   # resources :schedules
    #resources :shifts
    resources :travel_infos
    resources :clients
    resources :gc_contacts
    resources :project_managers
    resources :shift_managers
    resources :site_managers

    root to: "clients#index"  
  end

  resources :travel_infos
  resources :shifts
  resources :schedules
  
  
  
  

  resources :employee_lists
  

  resources :project_types
  resources :perdiems
  resources :expense_codes
  resources :projects 
    resources :rosters do
    resources :roster_lists 
   end

  
   
  resources :contacts
  resources :posts
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: 'projects#index'

  get 'new_store', :to => 'projects#new_store'
  get 'els', :to => 'projects#els'
  get 'fet', :to => 'projects#fet'

  get 'per_diem_info', :to => 'roster_lists#per_diem_info'

  get 'project_shifts', :to => 'projects#project_shifts'


  resources  'copy_roster_list', :to => 'rosters#copy_roster_list'
 

end

app/models/admin_user.rb
class AdminUser < User 
end

app/models/client.rb
class Client < Contact
	has_many :projects
end

app/models/contact.rb
class Contact < ApplicationRecord
end

app/models/employee.rb
class Employee < ApplicationRecord

has_many :perdiems
has_many :expense_codes
has_many :roster_lists


 def full_name
  	last_name.upcase + ", " + first_name.upcase
  end

end

app/models/employee_list.rb
class EmployeeList < ApplicationRecord
  belongs_to :roster
  has_many :expense_codes
  has_many :per_diems
  has_many :employees
end

app/models/expense_code.rb
class ExpenseCode < ApplicationRecord
  belongs_to :employee_list
end

app/models/gc_contact.rb
class GcContact < Contact 
end

app/models/perdiem.rb
class Perdiem < ApplicationRecord
  belongs_to :employee_list
end

app/models/post.rb
class Post < ActiveRecord::Base
	belongs_to :user , optional: true
	validates_presence_of :date, :rationale
end

app/models/project.rb
class Project < ApplicationRecord

	has_one :project_types
	has_many :rosters, inverse_of: :project
	has_many :travel_infos
	has_many :schedules
	has_many :states
	

	# class to combine columns to create project name
	def project_name
		company + project_type.to_s + client + store_num
	end


	def self.search(term)
	  if term
	    where('project_type LIKE ? OR client LIKE ?', "%#{term}%", "%#{term}%" )
	    
	  else
	    all
	  end
	end

end

app/models/project_type.rb
class ProjectType < ApplicationRecord

end

app/models/roster.rb
class Roster < ApplicationRecord
  belongs_to :project 
  has_many :roster_lists, :dependent => :destroy
  has_many :shift_infos
accepts_nested_attributes_for :roster_lists ,
							   allow_destroy: true,
							   reject_if: proc {|att| att['employee_id'].blank?}


def self.search(term)

	  if term
	    where("week = ?", "%#{term}%")
	      	    
	  else
	    all
	  end
	end

							  
end

app/models/roster_list.rb
class RosterList < ApplicationRecord
  belongs_to :roster, optional: true
  belongs_to :employee


def self.search(term)

	  if term
	    where("week = ?", "%#{term}%")
	      	    
	  else
	    all
	  end
	end



end

app/models/schedule.rb
class Schedule < ApplicationRecord
  belongs_to :project
  has_many :shifts
end

app/models/shift.rb
class Shift < ApplicationRecord
  belongs_to :schedule
  has_many :employees
end

app/models/shift_info.rb
class ShiftInfo < ApplicationRecord
  belongs_to :roster
end

app/models/site_manager.rb
class SiteManager < Contact
end

app/models/state.rb
class State < ApplicationRecord
  has_many :project
end

app/models/travel_info.rb
class TravelInfo < ApplicationRecord
  belongs_to :project
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :posts
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates_presence_of :first_name, :last_name

  def full_name
  	last_name.upcase + "," + first_name.upcase
  end
end

app/controllers/roster_lists_controller.rb
class RosterListsController < ApplicationController
  before_action :set_roster_list, only: [:show, :edit, :update, :destroy, :copy_to_next_week]

  # GET /roster_lists
  # GET /roster_lists.json
  def index

    @roster_lists = RosterList.search(params[:term])
  end

  # GET /roster_lists/1
  # GET /roster_lists/1.json
  def show
  end

  # GET /roster_lists/new
  def new
     @roster = Roster.find(params[:roster_id])
    @roster_list = RosterList.new

     
  end

  # GET /roster_lists/1/edit
  def edit
  end

  def per_diem_info
    @roster_lists = RosterList.joins(:roster).search(params[:term])
    @roster_lists = @roster_lists.where.not(perdiem: "")
   

  end 
 


  # POST /roster_lists
  # POST /roster_lists.json
  def create

    @roster = Roster.find(params[:roster_id])
    @roster_list = @roster.roster_lists.build(roster_list_params)  

        
     

      if @roster_list.save
          #      flash [:notice] = 'Roster list was successfully created.' 
      redirect_to roster_roster_lists_path(@roster_list)
      else
        render :action => 'new'
       end
  end

  # PATCH/PUT /roster_lists/1
  # PATCH/PUT /roster_lists/1.json
  def update
      @roster = Roster.find(params[:roster_id])
    respond_to do |format|
      if @roster_list.update(roster_list_params)
        format.html { redirect_to @roster_list, notice: 'Roster list was successfully updated.' }
        format.json { render :show, status: :ok, location: @roster_list }
      else
        format.html { render :edit }
        format.json { render json: @roster_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /roster_lists/1
  # DELETE /roster_lists/1.json
  def destroy
      @roster = Roster.find(params[:roster_id])
    @roster_list.destroy
    respond_to do |format|
      format.html { redirect_to roster_lists_url, notice: 'Roster list was successfully destroyed.' }
      format.json { head :no_content }
    end
  end






  private
    # Use callbacks to share common setup or constraints between actions.
    def set_roster_list
      @roster_list = RosterList.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def roster_list_params
      params.require(:roster_list).permit(:roster_id, :employee_id, :perdiem, :expense_code, :shift_id, :destroy)
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/roster_lists_helper.rb
module RosterListsHelper
end

app/views/roster_lists/_form.html.erb
<%= simple_form_for [@roster, @roster_list] do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
   

    <%= f.association :employee, label_method: :full_name%>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/roster_lists/copy_roster_list.html.erb
Roster info

<%=   @roster_lists.inspect    %>
<br>  

app/views/roster_lists/edit.html.erb
<h1>Editing Roster List</h1>

<%= render 'form', roster_list: @roster_list %>

<%= link_to 'Show', @project_roster_list %> |
<%= link_to 'Back', roster_lists_path %>

app/views/roster_lists/index.html.erb
 <div class = "panel panel-primary ">


<div class="panel-heading"> Roster Info </div>



  <div class="panel-body">

<%= form_tag(rosters_path , method: :get) do %>
  <%= date_field_tag :term, params[:term] %>
  <%= submit_tag 'Search', name: nil %>
<% end %>



<p id="notice"><%= notice %></p>





<table class = "table table-striped table-hover">
  <thead>
    <tr>
      <th>Week </th>
      <th>Employee</th>
      <th> Phone </th>
          <th>Per Diem</th>
              <th>Notes</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @roster_lists.each do |roster_list| %>
      <tr>
        <td><%= roster_list.roster.week %></td>
        <td><%= roster_list.employee.full_name %></td>
               <td><%= roster_list.employee.phone %></td>
        <td> <%= roster_list.perdiem %> </td>
        <td> Notes to be added  </td>
        <td> </td>
        <td><%= link_to 'Show', roster_list %></td>
        <td><%= link_to 'Edit', edit_roster_list_path(roster_list) %></td>
        <td><%= link_to 'Destroy', roster_list, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Roster List', new_roster_list_path %>

</div>
</div>
</div>

app/views/roster_lists/new.html.erb
<h1>New Roster List</h1>

<%= render 'form', roster_list: @roster_list %>
<%= link_to 'Back', roster_lists_path %>

app/views/roster_lists/per_diem_info.html.erb
<p id="notice"><%= notice %></p>

<h1>Per Diem Report </h1>

<%= form_tag(per_diem_info_path , method: :get) do %>
  <%= text_field_tag :term, params[:term] %>
  <%= submit_tag 'Search', name: nil %>
<% end %>



<table class = "table table-striped table-hover">
  <thead>
    <tr>
     
      <th> Week </th>
      <th>Employee</th>
      <th> Per Diem </th>
      <th> Note </th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @roster_lists.each do |roster_list| %>
      <tr>
       
       	<td><%= roster_list.roster.week %></td>
        <td><%= roster_list.employee.full_name %></td>
        <td><%= roster_list.perdiem %></td>
		<td><%= roster_list.employee.full_name %></td>


        <td><%= link_to 'Show', roster_list %></td>
        <td><%= link_to 'Edit', edit_roster_list_path(roster_list) %></td>
        <td><%= link_to 'Destroy', roster_list, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Roster List', new_roster_list_path %>

app/views/roster_lists/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Roster:</strong>
  <%= @roster_list.roster.id %>
</p>

<p>
  <strong>Roster:</strong>
  <%= @roster_list.roster.project_id %>
</p>

<p>
  <strong>Employee:</strong>
  <%= @roster_list.employee.full_name %>
</p>

<%= link_to 'Edit', edit_roster_list_path(@roster_list) %> |
<%= link_to 'Back', roster_lists_path %>